sonar.projectKey=Banco-BanQuito_banquito-web-personas-frontend
sonar.organization=banco-banquito
sonar.projectName=BanQuito Web Personas Frontend
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.*,**/*.spec.*
